version: '3.5'
services:
  #---------#
  # Traefik #
  #---------#
  traefik:
    container_name: traefik.local
    image: traefik:v2.9
    command: >
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entryPoints.http.address=":80"
      --accesslog
      --log.level=INFO
      --api=true
      --api.insecure=true
      --api.dashboard=true
    ports:
      # load balancer port
      - 16060:80
      # UI management port
      - 26060:8080
    labels:
      - traefik.http.routers.traefik.rule=Host(`localhost`)
    networks:
      - ecommerce-network
    volumes:
      # scan all running containers on the Docker socket (i.e., auto service discovery)
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  ecommerce-network:
    name: ecommerce-app