version: '3.5'
services:
  #------------------#
  # Producer Service #
  #------------------#
  product-service:
    container_name: product-service.local
    image: product-service:local
    ports:
      - 18080:8080
      - 18000:8000
    depends_on:
      - product-service-database
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  product-service-database:
    container_name: product-service-database.local
    image: postgres:14
    ports:
      - 15432:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=masterpass
  #-----------------------#
  # Shopping Cart Service #
  #-----------------------#
  shopping-cart-service:
    container_name: shopping-cart-service.local
    image: shopping-cart-service:local
    ports:
      - 28080:8080
      - 28000:8000
    depends_on:
      - shopping-cart-service-database
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  shopping-cart-service-database:
    container_name: shopping-cart-service-database.local
    image: postgres:14
    ports:
      - 25432:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=masterpass
  #---------------#
  # Order Service #
  #---------------#
  order-service:
    container_name: order-service.local
    image: order-service:local
    ports:
      - 38080:8080
      - 38000:8000
    depends_on:
      - order-service-database
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  order-service-database:
    container_name: order-service-database.local
    image: postgres:14
    ports:
      - 35432:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=masterpass
  #-----------------#
  # Payment Service #
  #-----------------#
  payment-service:
    container_name: payment-service.local
    image: payment-service:local
    ports:
      - 48080:8080
      - 48000:8000
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
networks:
  ecommerce-network:
    name: ecommerce-app