version: '3.5'
services:
  #------------------#
  # Producer Service #
  #------------------#
  product-service:
    container_name: product-service.local
    image: product-service:local
    ports:
      - 18080:8080
      - 18000:8000
    depends_on:
      - product-service-database
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  product-service-database:
    container_name: product-service-database.local
    image: postgres:14
    ports:
      - 15432:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=masterpass
  #-----------------------#
  # Shopping Cart Service #
  #-----------------------#
  shopping-cart-service:
    container_name: shopping-cart-service.local
    image: shopping-cart-service:local
    ports:
      - 28080:8080
      - 28000:8000
    depends_on:
      - shopping-cart-service-database
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  shopping-cart-service-database:
    container_name: shopping-cart-service-database.local
    image: postgres:14
    ports:
      - 25432:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=masterpass
  #---------------#
  # Order Service #
  #---------------#
  order-service:
    container_name: order-service.local
    image: order-service:local
    ports:
      - 38080:8080
      - 38000:8000
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
  #-----------------#
  # Confluent Kafka #
  #-----------------#
  # References:
  # - Cookbook: https://github.com/robcowart/docker_compose_cookbook
  # - Confluent Docker images: https://github.com/confluentinc/cp-docker-images
  zookeeper:
    container_name: zookeeper.local
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - 2181:2181
    networks:
      - ecommerce-network
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    container_name: kafka.local
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - 9092:29092
    networks:
      - ecommerce-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS=Orders:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  schema-registry:
    container_name: schema-registry.local
    image: confluentinc/cp-schema-registry:7.2.1
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    networks:
      - ecommerce-network
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=backward
networks:
  ecommerce-network:
    name: ecommerce-app