version: '3.5'
services:
  #------------------#
  # Producer Service #
  #------------------#
  product-service:
    container_name: product-service.local
    image: product-service:local
    ports:
      - 18070-18071:8080
      - 18000-18001:8000
    depends_on:
      - product-service-database
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.backend=product-service
      - traefik.http.routers.product-service.rule=Host(`localhost`) && PathPrefix(`/products`)
      - traefik.http.services.product-service.loadbalancer.server.port=8080
  #-----------------------#
  # Shopping Cart Service #
  #-----------------------#
  shopping-cart-service:
    container_name: shopping-cart-service.local
    image: shopping-cart-service:local
    ports:
      - 28080:8080
      - 28000:8000
    depends_on:
      - shopping-cart-service-database
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.backend=shopping-cart-service
      - traefik.http.routers.shopping-cart-service.rule=Host(`localhost`) && PathPrefix(`/cart`)
      - traefik.http.services.shopping-cart-service.loadbalancer.server.port=8080
  #---------------#
  # Order Service #
  #---------------#
  order-service:
    container_name: order-service.local
    image: order-service:local
    ports:
      - 38080:8080
      - 38000:8000
    depends_on:
      - order-service-database
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.backend=order-service
      - traefik.http.routers.order-service.rule=Host(`localhost`) && PathPrefix(`/orders`)
      - traefik.http.services.order-service.loadbalancer.server.port=8080
  #-----------------#
  # Payment Service #
  #-----------------#
  payment-service:
    container_name: payment-service.local
    image: payment-service:local
    ports:
      - 48080:8080
      - 48000:8000
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.backend=payment-service
      - traefik.http.routers.payment-service.rule=Host(`localhost`)
      - traefik.http.services.payment-service.loadbalancer.server.port=8080
networks:
  ecommerce-network:
    name: ecommerce-app