---
openapi: 3.0.3
info:
  title: eCommerce Shopping Cart Api
  version: "1.0"
paths:
  /cart/{cartId}:
    post:
      tags:
        - "Cart"
      summary: Add new item in the cart
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Cart content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartCreateDto'
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "500":
          description: Internal server error
    get:
      tags:
        - "Cart"
      summary: Return all items from the cart
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItemDto'
        "500":
          description: Internal server error
    delete:
      tags:
        - "Cart"
      summary: Delete all items from the cart
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not found
        "500":
          description: Internal server error
  /cart/{cartId}/items/{itemId}:
    get:
      tags:
        - "Item"
      summary: Return item from cart by id
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartCreateDto'
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
    put:
      tags:
        - "Item"
      summary: Update an item from cart by id
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Partial update content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartUpdateDto'
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
    delete:
      tags:
        - "Item"
      summary: Delete an item from cart by id
      parameters:
        - in: path
          name: cartId
          description: Cart Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
components:
  schemas:
    CartItemDto:
      type: object
      properties:
        itemId:
          type: string
          description: Cart item unique id
          format: uuid
      allOf:
        - $ref: '#/components/schemas/CartCreateDto'
    CartCreateDto:
      type: object
      properties:
        productId:
          type: string
          description: Product unique id
          format: uuid
        quantity:
          type: integer
          description: Product quantity
          example: 100
        discount:
          type: number
          description: Discount on percentage rate
          example: 25
    CartUpdateDto:
      type: object
      properties:
        quantity:
          type: integer
          description: Cart quantity
          example: 2